return {
    "williamboman/mason.nvim",
    opts = {
        ensure_installed = {
            "angular-language-server",
            "csharp-language-server",
            "csharpier",
            "debugpy",
            "delve",
            "dockerfile-language-server",
            "eslint-lsp",
            "eslint_d",
            "gopls",
            "html-lsp",
            "jq",
            "lua-language-server",
            "mypy",
            "mypy",
            "prettierd",
            "pyright",
            "ruff",
            "ruff-lsp",
            "rust-analyzer",
            "shfmt",
            "sonarlint-language-server",
            "stylua",
            "tailwindcss-language-server",
            "typescript-language-server",
        },
    },
}
